services:
  nginx:
    image: nginx:1.27-alpine
    container_name: yii2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UID: ${PHP_UID}
        GID: ${PHP_GID}
    container_name: yii2_php
    volumes:
      - ./src:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=512M
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: yii2_mysql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: